### Afficher tous les utilisateurs
GET http://localhost:3000/api/users

### Créer un utilisateur
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "name": "Paul",
  "email": "Paul@mail.com",
  "password": "123456"
}

### Login utilisateur
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "raph@gmail.com",
  "password": "123"
}

//
### DELETE a user
DELETE http://localhost:3000/api/users/68110ead16534165a45ea1fc
Authorization: Bearer eyJhbGciOiJIUzI1NiIs



### Afficher tous les voitures
GET http://localhost:3000/api/cars/available


#####
POST http://localhost:3000/api/cars
Content-Type: application/json
 
 {
  "marque": "JEEP",
  "modele": "Cherokee",
  "annee": 2025,
  "prix": 86,
  "disponible": true,
  "description": "SUV tout-terrain avec système 4x4 Jeep Active Drive, Uconnect 6 et capacités Trail Rated"
}

###supprimer une voitures avec l'id 
DELETE http://localhost:3000/api/cars/681114977ab7b8bc3b31b02a


##reserver une voitures 
### Créer une nouvelle réservation
POST http://localhost:3000/api/reservations
Content-Type: application/json

{
  "voiture": "681114977ab7b8bc3b31b02a",
  "utilisateur": "68110ead16534165a45ea1fc",
  "dateDebut": "2025-05-01",
  "dateFin": "2025-05-10"
}