### Afficher tous les utilisateurs
GET http://localhost:3000/api/users

### Créer un utilisateur
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "name": "Paul",
  "email": "Paul@mail.com",
  "password": "123456"
}
//
### DELETE a user
DELETE http://localhost:3000/users/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNzMwODI2NTU5fQ.U4b3KbZVxUx5YCvH5otB6ILYYdimspDHptHRzVnPJlQ



### Afficher tous les voitures
GET http://localhost:3000/api/cars/available


#####
POST http://localhost:3000/api/cars
Content-Type: application/json

{
    "marque": "BMW",
    "modele": "A3",
    "annee": 2021,
    "prix": 26500,
    "disponible": false,
    "description": "Audi A3 Sportback avec intérieur cuir"
}

###supprimer une voitures avec l'id 
DELETE http://localhost:3000/api/cars/6810c32a93cdb506cfe9fb76